apiVersion: v1
kind: Namespace
metadata:
  name: microservices-201700761
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-genderize
  namespace: microservices-201700761
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-genderize
  template:
    metadata:
      labels:
        app: service-genderize
    spec:
      containers:
        - name: service-genderize
          image: epum/genderize:latest
          ports:
            - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: service-genderize
  namespace: microservices-201700761
spec:
  selector:
    app: service-genderize
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002