name: release delivery

on:
  push:
    branches:
      - "release" # Run on release branch
      - "release/*" # Ejecutar en todas las ramas de versión

jobs:
  release-delivery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Paso de construcción
      - name: Build
        run: |
          cd practica3
          docker build -t epum/agifiy:latest -f agify.dockerfile .
          docker build -t epum/genderize:latest -f genderize.dockerfile .
          docker build -t epum/main:latest -f main.dockerfile .
          echo "All images built successfully!"

      # Paso de prueba (puedes agregar tus propios pasos de prueba aquí)
      - name: Test
        run: |
          echo "Running tests..."
          echo "All tests passed successfully!"

      # Paso de entrega
      - name: Deliver
        run: |
          docker push epum/agifiy:latest
          docker push epum/genderize:latest
          docker push epum/main:latest
          echo "Images delivered successfully!"